cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),
]

ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopping/',include('shopping.urls')),
    path('search',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns=[
    path('',views.searchResult,name='searchResult'),
]

shopping/urls.py
from django.urls import path,include
from . import views
app_name='shopping'
urlpatterns = [
    path('', views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.productdetail,name='product_category_detail'),

]

cart/models.py
from django.db import models
from shopping.models import product

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='cart'
        ordering= ['date_added']
    def __str__(self):
        return '{}'.format (self.cart_id)

class CartItem(models.Model):
    products=models.ForeignKey(product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.products.price * self.quantity
    def __str__(self):
        return '{}'.format (self.products)

search_app/models.py
from django.db import models

# Create your models here.

shopping/models.py
from django.db import models
from django.urls import reverse
class category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shopping:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class product(models.Model):
    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('shopping:product_category_detail',args=[self.category.slug,self.slug])
    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural='products'
    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render,redirect,get_object_or_404
from shopping.models import product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return  cart

def add_cart(request,product_id):
    products=product.objects.get(id=product_id)
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart=Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save(),
    try:
        cart_item=CartItem.objects.get(products=products,cart=cart)
        if cart_item.quantity < cart_item.products.stock:
            cart_item.quantity +=1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            products=products,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):

    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)

        for cart_item in cart_items:
            total+=(cart_item.products.price * cart_item.quantity)
            counter +=cart_item.quantity

    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    products=get_object_or_404(product,id=product_id)
    cart_item=CartItem.objects.get(products=products,cart=cart)
    if cart_item.quantity >1:
        cart_item.quantity -=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    products = get_object_or_404(product, id=product_id)
    cart_item = CartItem.objects.get(products=products, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render
from shopping.models import product
from django.db.models import Q


def searchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query= request.GET.get('q')
        products=product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'search.html',{'query':query,'products':products})

shopping/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import category,product
from django.core.paginator import Paginator,EmptyPage,InvalidPage

def allprodcat(request,c_slug=None):
    c_page=None
    products_list=None
    if c_slug!=None:
        c_page=get_object_or_404(category,slug=c_slug)
        products_list=product.objects.all().filter(category=c_page,available=True)
    else:
        products_list=product.objects.all().filter(available=True)
    paginator=Paginator(products_list,6)
    try:
            page=int(request.GET.get('page','1'))
    except:
            page=1
    try:
            products=paginator.page(page)
    except (EmptyPage,InvalidPage):
            products=paginator.page(paginator.num_pages)

    return render(request,"category.html",{'category':c_page,'products':products})

def productdetail(request,c_slug,product_slug):
    try:
        products=product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as e:
        raise  e
    return  render(request,'product.html',{'product':products})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div>
{% include 'header.html' %}
{% include 'navbar.html' %}

{% block content %}
{% endblock %}
</div>

{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
SHOPPING CART
{% endblock %}
{% block title %}
CART - AJ SHOPPI
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">
      Your Shopping Cart is Empty
    </h1>
    <br>
    <p class="text-center">
      please Click <a href="{% url 'shopping:allprodcat' %}">here</a> to continue shopping.

    </p>

  </div>
</div>
{% else %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">
      YOUR SHOPPING CART
    </h1>
    <br>
  </div>

  <div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
          <th colspan="5">
            Your Items
          </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
          <td>
            <a href="cart_item.products.get_absolute_url"><img src="{{cart_item.products.image.url}}"  alt="" style="width:100px; height:100px;" class="float-left rounded custom_image"></a>

          </td>
          <td class="text-left">
            {{cart_item.products.name}}
            <br>
            SKU:{{cart_item.product.id}}
            <br>
            PRICE: $ {{cart_item.products.price}}
            <br>
            Qty: {{cart_item.quantity}} X $ {{cart_item.products.price}}
            <br>
          </td>
          <td>
            $ {{cart_item.sub_total}}

          </td>
          {% if cart_item.quantity < cart_item.products.stock %}
          <td>

            &nbsp;<a href="{% url 'cart:add_cart' cart_item.products.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:full_remove' cart_item.products_id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
             &nbsp;<a href="{% url 'cart:cart_remove' cart_item.products_id %}" class="custom_a"><i class="fa fa-minus custom_icons" ></i></a>
          </td>
          {% else %}
          <td>
            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.products_id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.products_id %}" class="custom_icon"><i class="fa fa-trash custom_icon"></i></a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
  <table class="table my_custom_table">
    <thead class="my_custom_thead">
    <tr>
      <th>
        CHECKOUT
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        Please review your cart items before proceeding with payment.
      </td>
    </tr>
    <tr>
      <td class="text-left">
         Total item = <strong> {{ counter }}</strong>
      </td>
    </tr>
    <tr>
      <td class="text-left">
        Your Total Amount = <strong> {{ total }}
      </strong>

      </td>
    </tr>
    </tbody>
  </table>
<div class="mx_auto">
  <a href="{% url 'shopping:allprodcat' %}" class="btn btn-secondary btn-block my_custom_button">Continue shopping</a>
</div>

  </div>
  {% endif %}
  </div>
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
{{ category.description|truncatewords:155}}
{% else %}
welcome to AJ store where you can buy...
{% endif %}
{% endblock %}

{% block title %}
{% if category %}
{{ category.name}} - AJ Store
{% else %}
new collections.. - AJ store
{% endif %}
{% endblock %}

{% block content %}
{% if category %}
<div>
    <div class="row my_row class">
        <div class="mx_auto">

        <p><a href="{% url 'shopping:allprodcat' %}">OUR PRODUCT COLLECTIONS</a></p>
        </div>
    </div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}
    <div class="container">
        <div class="">
    <img class="my_images" src="{{category.image.url}}" width="300" height="300" alt="{{category.name}}">
</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'img/banner.png' %}" width="1480" height="350" alt="our products">
</div>
<br>
<div>
    <h1 class="text-center my_title"> our product collections</h1>
    <p class="text-justify">The Lorem ipum filling text is used by graphic designers, programmers and printers with the aim of occupying the spaces of a website, an advertising product or an editorial production whose final text is not yet ready.</p>

</div>
    </div>
</div>
{% endif %}
<div class="container">
    <div class="row mx_auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-6 col-sm-9 col-md-8 col-lg-4">
            <div class="card text-center" style="width:20rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" width="70" height="250" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>

        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>
{% endblock %}

templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; shopi tech pvt ltd.All rights Reserved</p>
</div>

templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shopping:allprodcat' %}"> <img src="{% static 'img/logo.png' %}" width="100" height="100" align="center" alt="logoimage"></a>
  </center>
</header>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shopping:allprodcat' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'shopping:allprodcat' %}">shop</a>
      </li>
      <li class="nav-item dropdown {% if 'shopping' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          DROP-DOWN
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'shopping:allprodcat' %}">ALL_Products</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
           {% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-cart-arrow-down"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-2" action="{% url 'search_app:searchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-2" type="submit"><i class="fa fa-search"></i></button>
    </form>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{{ product.description|truncatewords:155}}
{% endblock %}
{% block title %}
{% if category %}
{{product.name}} - AJ Store
{% else %}
new
{% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
<div class="mx_auto">
        <p> <a href="{% url 'shopping:allprodcat' %}"><b>HOME</b></a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
</div>
    <div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" width="300" height="300" alt="{{product.name}}">

        </div>
    </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_prod_title">{{product.name}}</h1>
            <p>${{product.price}}</p>
            <p class="my_title">product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_prod_text"><b>Out Of Stock</b></p>
            {% else %}
                <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart </a>
            {% endif %}
        </div>
    </div>
</div>
</div>
</div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
 we have variety of products.
{% endblock %}
{% block title %}
search
{% endblock %}
{% block content %}
<div>
 <p class="text-center my_search_text"> you have searched for:<b>"{{query}}"</b></p>
</div>
<div class="container">
    <div class="row mx_auto">
        {% for product in products %}
        <div class="my_bottom_margin col-6 col-sm-9 col-md-8 col-lg-4">
            <div class="card text-center" style="width:20rem;">
                <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" width="70" height="250" alt="{{product.name}}"> </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
     {% empty %}
     <div class="row mx_auto">
      <p class="text-center my_search_text">no result found</p>
     </div>
        {% endfor %}
    </div>
</div>
{% endblock %}